### PR TITLE
Cleaned up to standards (General standards & https://github.com/twitter/recess)

### PR DESCRIPTION
**Pull request by m1**
Also added LICENSE

### CODE REVIEW

**Comment by causal-agent** [comment]
I don't really see the point in most of these changes, other than moving the license text out of the comment.

**Comment by m1** [comment]
Well it's kind of a mess atm, just trying to make it conform to a standard rather than just random ordering of properties and the like.

**Comment by causal-agent** [comment]
I'll try to clean it up, but I'd rather do it manually. Thanks anyway.

**Comment by m1** [comment]
It has been done manually. Just saying.

**Pull request closed without merging**
