### PR TITLE
Replace all `ch` values with `rem`

### PR DESCRIPTION
**Pull request by halbgut**
Support for `ch` is pretty [dire](https://developer.mozilla.org/en-US/docs/Web/CSS/length#Browser_compatibility). So I propose replacing them with `rem`.

### CODE REVIEW

**Comment by causal-agent** [comment]
From the README:

> Writ is designed for modern, standards compliant browsers only. There are no compatibility hacks. Writ is tested on the latest stable releases of Safari, Chrome and Firefox.

Regardless, that compatibility chart seems far from "dire".

**Comment by halbgut** [comment]
I don't see any advantages in using `ch` could you explain?

**Comment by causal-agent** [comment]
The advantage is in "say what you mean". Widths being proportional to character width is what makes sense.

**Comment by halbgut** [comment]
Hmm, I see how that makes perfect sense for monospaced fonts. In **writ** though you're mostly using proportionally spaced fonts. So you can never be sure how many characters are on a line. You can only approximate it (sorry if this is confusing, I'm trying to follow your rational). So IMO the advantages of using `rem` are far bigger than this _potential advantage_. Also, browsers will fall back to using `.5rem` when [_"it is impossible or impractical to determine the measure of the "0" glyph"_](https://www.w3.org/TR/css3-values/#font-relative-lengths). IDK how often that happens. The only thing I know, is that in FF Developer Edition `.5rem === 1ch` when using **writ**.

Sorry if I'm bothering you, but I think it's an interesting discussion. :)

**Comment by causal-agent** [comment]
I'd much rather be saying "I want approximately 78 characters per line" than "I want exactly as many characters per line as fit sideways in the height of 39 lines". It has a more useful semantic meaning.

If browsers fall back to `0.5rem`, I see no issue. That comes to the same thing as this PR, except using `ch` preserves the intention.

**Comment by halbgut** [comment]
You're right, that's a good argument. Though I'd say the disadvantages of using `ch` are much bigger than the ones of `rem`. It's your project so reject the PR if you want. I'll be using my fork in the future though, since the layout being broken on Android isn't really an option for me.

**Comment by causal-agent** [comment]
I don't see anything being broken on Android. I'm currently testing Galaxy Tab 4 (4.4), Nexus 6 (5), HTC One M8 (4.4) with BrowserStack.

**Comment by solson** [comment]
I don't notice any particular issues on my Nexus 5, either. (Android Lollipop, Chrome browser.)

**Comment by halbgut** [comment]
I tested it through BrowserStack and you are (of course) correct, the android browser does support `ch`. My initial concern of _Browser Support_ was misguided. I seem to have misread MDNs browser support table. As I understand, currently _Chrome_ is the standard browser on most Android phones. I'm very sorry! I'm closing the PR.

**Pull request closed without merging**
